### ISSUE TITLE
Proposal: remove the `sudo gem ...` protection?

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-ruby#1]
Before OS X 10.11 it was possible to "accidentally" install gems into system ruby. With the advent of [System Integrity Protection](https://support.apple.com/en-us/HT204899) I don't think this is necessary.

See: 
- https://github.com/pivotal-sprout/sprout-ruby/blob/master/recipes/no_sudo_gem.rb
  - https://github.com/pivotal-sprout/sprout-ruby/blob/master/templates/default/gem_setup-warn_on_sudo.bash#L2

**Comment by nertzy** [comment]
:+1:

**Comment by wendorf** [comment]
It'd be nice to remove this, but I'm not too aware of the history of the sudo gem protection. Can you explain why SIP unnecessitates this?

**Comment by aramprice** [comment]
With SIP it is no longer possible to modify `/usr/bin` (anything under `/usr`?) so there is already a stumbling block (like this warning) when a user runs `sudo gem install blah`.

In the case of this warning, on a non-SIP system, simply "un-aliasing" `sudo` works, ex:
`\sudo gem install blah`

On a SIP protected system the user needs to specify an alternate location for binaries, ex:
`sudo gem install blah -n /usr/local/bin # => or similar writeable dir`
