### ISSUE TITLE
Proposal: stop installing `gemrc` into `/etc`

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-ruby#2]
Currently we install a system-wide `gemrc` into `/etc` (https://github.com/pivotal-sprout/sprout-ruby/blob/master/recipes/gemrc.rb#L1) and then symlink this into the `sprout.user`s home directory (https://github.com/pivotal-sprout/sprout-ruby/blob/master/recipes/gemrc.rb#L9).

This may be problematic with [System Integrity Protection](https://support.apple.com/en-us/HT204899) (now/eventually?), and it also seems to be more invasive of the OS than is strictly necessary.

Further if [SIP](https://support.apple.com/en-us/HT204899) prevents installation of gems into the (global) system ruby locations simply having a `gemrc` file in `sprout.user` home directory is probably sufficient.

**Comment by nertzy** [comment]
Yeah I see no reason at all to touch `/etc/gemrc`

**Comment by hiremaga** [comment]
Shall we change this to leave /etc/gemrc alone and write $HOME/.gemrc
instead?

I like having ri and rdoc disabled by default since that speeds up gem
installation considerably.

**Comment by aramprice** [comment]
@hiremaga I definitely agree that these settings speed things up, and I wouldn't want to give them up.

I don't know if there is generally/usually an `/etc/gemrc`so simply modifying the recipe to be:

``` ruby
file "#{node['sprout']['home']}/.gemrc" do
  owner node['sprout']['user']
  owner node['sprout']['group'] # <= is this a thing?
  mode '0644'
  action :create
  content "install: --no-rdoc --no-ri\nupdate: --no-rdoc --no-ri\n"
end
```

should provide the benefits without disturbing the system.

I suspect that this was put in `/etc/gemrc` as a way to ensure that this setting would be used when installing system gems - but that's a discouraged practice  so maybe not so crucial. also  [System Integrity Protection](https://support.apple.com/en-us/HT204899) might make installing system gems (into system locations) no longer possible.

**Comment by nertzy** [comment]
Yeah I think we should write `$HOME/.gemrc`.

I also seem to remember that Bundler adds `--no-rdoc --no-ri` by default, so this would likely only impact people who run `gem install` directly. So probably not a huge difference either way.

**Comment by hiremaga** [comment]
That change looks great @aram

Good to know bundler adds this, it'd be nice to keep this for times install
gems by hand - e.g. bosh_cli on CF
